# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exporter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xporter.proto\x12\x1forg.eclipse.ecf.python.protobuf\"\xf0\x02\n\rExportRequest\x12\x13\n\x0bmodule_name\x18\x01 \x01(\t\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12W\n\rcreation_args\x18\x03 \x03(\x0b\x32@.org.eclipse.ecf.python.protobuf.ExportRequest.CreationArgsEntry\x12j\n\x17overriding_export_props\x18\x04 \x03(\x0b\x32I.org.eclipse.ecf.python.protobuf.ExportRequest.OverridingExportPropsEntry\x1a\x33\n\x11\x43reationArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a<\n\x1aOverridingExportPropsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\x0e\x45xportResponse\x12\x13\n\x0b\x65ndpoint_id\x18\x01 \x01(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t\"&\n\x0fUnexportRequest\x12\x13\n\x0b\x65ndpoint_id\x18\x01 \x01(\t\"I\n\x10UnexportResponse\x12\x13\n\x0b\x65ndpoint_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exporter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EXPORTREQUEST']._serialized_start=52
  _globals['_EXPORTREQUEST']._serialized_end=420
  _globals['_EXPORTREQUEST_CREATIONARGSENTRY']._serialized_start=307
  _globals['_EXPORTREQUEST_CREATIONARGSENTRY']._serialized_end=358
  _globals['_EXPORTREQUEST_OVERRIDINGEXPORTPROPSENTRY']._serialized_start=360
  _globals['_EXPORTREQUEST_OVERRIDINGEXPORTPROPSENTRY']._serialized_end=420
  _globals['_EXPORTRESPONSE']._serialized_start=422
  _globals['_EXPORTRESPONSE']._serialized_end=482
  _globals['_UNEXPORTREQUEST']._serialized_start=484
  _globals['_UNEXPORTREQUEST']._serialized_end=522
  _globals['_UNEXPORTRESPONSE']._serialized_start=524
  _globals['_UNEXPORTRESPONSE']._serialized_end=597
# @@protoc_insertion_point(module_scope)
