// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hellomsg.proto

package org.eclipse.ecf.examples.protobuf.hello;

public final class Hellomsg {
  private Hellomsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloMsgContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string h = 1;</code>
     */
    boolean hasH();
    /**
     * <code>optional string h = 1;</code>
     */
    java.lang.String getH();
    /**
     * <code>optional string h = 1;</code>
     */
    com.google.protobuf.ByteString
        getHBytes();

    /**
     * <code>optional string f = 2;</code>
     */
    boolean hasF();
    /**
     * <code>optional string f = 2;</code>
     */
    java.lang.String getF();
    /**
     * <code>optional string f = 2;</code>
     */
    com.google.protobuf.ByteString
        getFBytes();

    /**
     * <code>optional string to = 3;</code>
     */
    boolean hasTo();
    /**
     * <code>optional string to = 3;</code>
     */
    java.lang.String getTo();
    /**
     * <code>optional string to = 3;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>optional string hellomsg = 4;</code>
     */
    boolean hasHellomsg();
    /**
     * <code>optional string hellomsg = 4;</code>
     */
    java.lang.String getHellomsg();
    /**
     * <code>optional string hellomsg = 4;</code>
     */
    com.google.protobuf.ByteString
        getHellomsgBytes();

    /**
     * <code>repeated double x = 5;</code>
     */
    java.util.List<java.lang.Double> getXList();
    /**
     * <code>repeated double x = 5;</code>
     */
    int getXCount();
    /**
     * <code>repeated double x = 5;</code>
     */
    double getX(int index);
  }
  /**
   * Protobuf type {@code org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent}
   */
  public  static final class HelloMsgContent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
      HelloMsgContentOrBuilder {
    // Use HelloMsgContent.newBuilder() to construct.
    private HelloMsgContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloMsgContent() {
      h_ = "";
      f_ = "";
      to_ = "";
      hellomsg_ = "";
      x_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloMsgContent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              h_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              f_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              to_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              hellomsg_ = bs;
              break;
            }
            case 41: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                x_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000010;
              }
              x_.add(input.readDouble());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                x_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                x_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          x_ = java.util.Collections.unmodifiableList(x_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.class, org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.Builder.class);
    }

    private int bitField0_;
    public static final int H_FIELD_NUMBER = 1;
    private volatile java.lang.Object h_;
    /**
     * <code>optional string h = 1;</code>
     */
    public boolean hasH() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string h = 1;</code>
     */
    public java.lang.String getH() {
      java.lang.Object ref = h_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          h_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string h = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHBytes() {
      java.lang.Object ref = h_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        h_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int F_FIELD_NUMBER = 2;
    private volatile java.lang.Object f_;
    /**
     * <code>optional string f = 2;</code>
     */
    public boolean hasF() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string f = 2;</code>
     */
    public java.lang.String getF() {
      java.lang.Object ref = f_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          f_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string f = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFBytes() {
      java.lang.Object ref = f_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        f_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 3;
    private volatile java.lang.Object to_;
    /**
     * <code>optional string to = 3;</code>
     */
    public boolean hasTo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string to = 3;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          to_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string to = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HELLOMSG_FIELD_NUMBER = 4;
    private volatile java.lang.Object hellomsg_;
    /**
     * <code>optional string hellomsg = 4;</code>
     */
    public boolean hasHellomsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string hellomsg = 4;</code>
     */
    public java.lang.String getHellomsg() {
      java.lang.Object ref = hellomsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hellomsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hellomsg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHellomsgBytes() {
      java.lang.Object ref = hellomsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hellomsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int X_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Double> x_;
    /**
     * <code>repeated double x = 5;</code>
     */
    public java.util.List<java.lang.Double>
        getXList() {
      return x_;
    }
    /**
     * <code>repeated double x = 5;</code>
     */
    public int getXCount() {
      return x_.size();
    }
    /**
     * <code>repeated double x = 5;</code>
     */
    public double getX(int index) {
      return x_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, h_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, f_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hellomsg_);
      }
      for (int i = 0; i < x_.size(); i++) {
        output.writeDouble(5, x_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, h_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, f_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, hellomsg_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getXList().size();
        size += dataSize;
        size += 1 * getXList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent)) {
        return super.equals(obj);
      }
      org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent other = (org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent) obj;

      boolean result = true;
      result = result && (hasH() == other.hasH());
      if (hasH()) {
        result = result && getH()
            .equals(other.getH());
      }
      result = result && (hasF() == other.hasF());
      if (hasF()) {
        result = result && getF()
            .equals(other.getF());
      }
      result = result && (hasTo() == other.hasTo());
      if (hasTo()) {
        result = result && getTo()
            .equals(other.getTo());
      }
      result = result && (hasHellomsg() == other.hasHellomsg());
      if (hasHellomsg()) {
        result = result && getHellomsg()
            .equals(other.getHellomsg());
      }
      result = result && getXList()
          .equals(other.getXList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasH()) {
        hash = (37 * hash) + H_FIELD_NUMBER;
        hash = (53 * hash) + getH().hashCode();
      }
      if (hasF()) {
        hash = (37 * hash) + F_FIELD_NUMBER;
        hash = (53 * hash) + getF().hashCode();
      }
      if (hasTo()) {
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getTo().hashCode();
      }
      if (hasHellomsg()) {
        hash = (37 * hash) + HELLOMSG_FIELD_NUMBER;
        hash = (53 * hash) + getHellomsg().hashCode();
      }
      if (getXCount() > 0) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + getXList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
        org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.class, org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.Builder.class);
      }

      // Construct using org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        h_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        f_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        hellomsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        x_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor;
      }

      public org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent getDefaultInstanceForType() {
        return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.getDefaultInstance();
      }

      public org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent build() {
        org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent buildPartial() {
        org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent result = new org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.h_ = h_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.f_ = f_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hellomsg_ = hellomsg_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          x_ = java.util.Collections.unmodifiableList(x_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.x_ = x_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent) {
          return mergeFrom((org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent other) {
        if (other == org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.getDefaultInstance()) return this;
        if (other.hasH()) {
          bitField0_ |= 0x00000001;
          h_ = other.h_;
          onChanged();
        }
        if (other.hasF()) {
          bitField0_ |= 0x00000002;
          f_ = other.f_;
          onChanged();
        }
        if (other.hasTo()) {
          bitField0_ |= 0x00000004;
          to_ = other.to_;
          onChanged();
        }
        if (other.hasHellomsg()) {
          bitField0_ |= 0x00000008;
          hellomsg_ = other.hellomsg_;
          onChanged();
        }
        if (!other.x_.isEmpty()) {
          if (x_.isEmpty()) {
            x_ = other.x_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureXIsMutable();
            x_.addAll(other.x_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object h_ = "";
      /**
       * <code>optional string h = 1;</code>
       */
      public boolean hasH() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string h = 1;</code>
       */
      public java.lang.String getH() {
        java.lang.Object ref = h_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            h_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string h = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHBytes() {
        java.lang.Object ref = h_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          h_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string h = 1;</code>
       */
      public Builder setH(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        h_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string h = 1;</code>
       */
      public Builder clearH() {
        bitField0_ = (bitField0_ & ~0x00000001);
        h_ = getDefaultInstance().getH();
        onChanged();
        return this;
      }
      /**
       * <code>optional string h = 1;</code>
       */
      public Builder setHBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        h_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object f_ = "";
      /**
       * <code>optional string f = 2;</code>
       */
      public boolean hasF() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string f = 2;</code>
       */
      public java.lang.String getF() {
        java.lang.Object ref = f_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            f_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string f = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFBytes() {
        java.lang.Object ref = f_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          f_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string f = 2;</code>
       */
      public Builder setF(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string f = 2;</code>
       */
      public Builder clearF() {
        bitField0_ = (bitField0_ & ~0x00000002);
        f_ = getDefaultInstance().getF();
        onChanged();
        return this;
      }
      /**
       * <code>optional string f = 2;</code>
       */
      public Builder setFBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        f_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>optional string to = 3;</code>
       */
      public boolean hasTo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string to = 3;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            to_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string to = 3;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string to = 3;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 3;</code>
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 3;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        to_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hellomsg_ = "";
      /**
       * <code>optional string hellomsg = 4;</code>
       */
      public boolean hasHellomsg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string hellomsg = 4;</code>
       */
      public java.lang.String getHellomsg() {
        java.lang.Object ref = hellomsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hellomsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hellomsg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHellomsgBytes() {
        java.lang.Object ref = hellomsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hellomsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hellomsg = 4;</code>
       */
      public Builder setHellomsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        hellomsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hellomsg = 4;</code>
       */
      public Builder clearHellomsg() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hellomsg_ = getDefaultInstance().getHellomsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hellomsg = 4;</code>
       */
      public Builder setHellomsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        hellomsg_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> x_ = java.util.Collections.emptyList();
      private void ensureXIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          x_ = new java.util.ArrayList<java.lang.Double>(x_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated double x = 5;</code>
       */
      public java.util.List<java.lang.Double>
          getXList() {
        return java.util.Collections.unmodifiableList(x_);
      }
      /**
       * <code>repeated double x = 5;</code>
       */
      public int getXCount() {
        return x_.size();
      }
      /**
       * <code>repeated double x = 5;</code>
       */
      public double getX(int index) {
        return x_.get(index);
      }
      /**
       * <code>repeated double x = 5;</code>
       */
      public Builder setX(
          int index, double value) {
        ensureXIsMutable();
        x_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double x = 5;</code>
       */
      public Builder addX(double value) {
        ensureXIsMutable();
        x_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double x = 5;</code>
       */
      public Builder addAllX(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureXIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, x_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double x = 5;</code>
       */
      public Builder clearX() {
        x_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
    }

    // @@protoc_insertion_point(class_scope:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
    private static final org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent();
    }

    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HelloMsgContent>
        PARSER = new com.google.protobuf.AbstractParser<HelloMsgContent>() {
      public HelloMsgContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HelloMsgContent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloMsgContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloMsgContent> getParserForType() {
      return PARSER;
    }

    public org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016hellomsg.proto\022\'org.eclipse.ecf.exampl" +
      "es.protobuf.hello\"P\n\017HelloMsgContent\022\t\n\001" +
      "h\030\001 \001(\t\022\t\n\001f\030\002 \001(\t\022\n\n\002to\030\003 \001(\t\022\020\n\010hellom" +
      "sg\030\004 \001(\t\022\t\n\001x\030\005 \003(\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor,
        new java.lang.String[] { "H", "F", "To", "Hellomsg", "X", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
