// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hellomsg.proto
// Protobuf Java Version: 4.30.2

package org.eclipse.ecf.examples.protobuf.hello;

public final class Hellomsg {
  private Hellomsg() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Hellomsg.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloMsgContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string h = 1;</code>
     * @return The h.
     */
    java.lang.String getH();
    /**
     * <code>string h = 1;</code>
     * @return The bytes for h.
     */
    com.google.protobuf.ByteString
        getHBytes();

    /**
     * <code>string f = 2;</code>
     * @return The f.
     */
    java.lang.String getF();
    /**
     * <code>string f = 2;</code>
     * @return The bytes for f.
     */
    com.google.protobuf.ByteString
        getFBytes();

    /**
     * <code>string to = 3;</code>
     * @return The to.
     */
    java.lang.String getTo();
    /**
     * <code>string to = 3;</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>string hellomsg = 4;</code>
     * @return The hellomsg.
     */
    java.lang.String getHellomsg();
    /**
     * <code>string hellomsg = 4;</code>
     * @return The bytes for hellomsg.
     */
    com.google.protobuf.ByteString
        getHellomsgBytes();

    /**
     * <code>repeated double x = 5;</code>
     * @return A list containing the x.
     */
    java.util.List<java.lang.Double> getXList();
    /**
     * <code>repeated double x = 5;</code>
     * @return The count of x.
     */
    int getXCount();
    /**
     * <code>repeated double x = 5;</code>
     * @param index The index of the element to return.
     * @return The x at the given index.
     */
    double getX(int index);
  }
  /**
   * Protobuf type {@code org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent}
   */
  public static final class HelloMsgContent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
      HelloMsgContentOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        HelloMsgContent.class.getName());
    }
    // Use HelloMsgContent.newBuilder() to construct.
    private HelloMsgContent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HelloMsgContent() {
      h_ = "";
      f_ = "";
      to_ = "";
      hellomsg_ = "";
      x_ = emptyDoubleList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.class, org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.Builder.class);
    }

    public static final int H_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object h_ = "";
    /**
     * <code>string h = 1;</code>
     * @return The h.
     */
    @java.lang.Override
    public java.lang.String getH() {
      java.lang.Object ref = h_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        h_ = s;
        return s;
      }
    }
    /**
     * <code>string h = 1;</code>
     * @return The bytes for h.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHBytes() {
      java.lang.Object ref = h_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        h_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int F_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object f_ = "";
    /**
     * <code>string f = 2;</code>
     * @return The f.
     */
    @java.lang.Override
    public java.lang.String getF() {
      java.lang.Object ref = f_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        f_ = s;
        return s;
      }
    }
    /**
     * <code>string f = 2;</code>
     * @return The bytes for f.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFBytes() {
      java.lang.Object ref = f_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        f_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object to_ = "";
    /**
     * <code>string to = 3;</code>
     * @return The to.
     */
    @java.lang.Override
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>string to = 3;</code>
     * @return The bytes for to.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HELLOMSG_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object hellomsg_ = "";
    /**
     * <code>string hellomsg = 4;</code>
     * @return The hellomsg.
     */
    @java.lang.Override
    public java.lang.String getHellomsg() {
      java.lang.Object ref = hellomsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hellomsg_ = s;
        return s;
      }
    }
    /**
     * <code>string hellomsg = 4;</code>
     * @return The bytes for hellomsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHellomsgBytes() {
      java.lang.Object ref = hellomsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hellomsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int X_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.DoubleList x_ =
        emptyDoubleList();
    /**
     * <code>repeated double x = 5;</code>
     * @return A list containing the x.
     */
    @java.lang.Override
    public java.util.List<java.lang.Double>
        getXList() {
      return x_;
    }
    /**
     * <code>repeated double x = 5;</code>
     * @return The count of x.
     */
    public int getXCount() {
      return x_.size();
    }
    /**
     * <code>repeated double x = 5;</code>
     * @param index The index of the element to return.
     * @return The x at the given index.
     */
    public double getX(int index) {
      return x_.getDouble(index);
    }
    private int xMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(h_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, h_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(f_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, f_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(to_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, to_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hellomsg_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, hellomsg_);
      }
      if (getXList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(xMemoizedSerializedSize);
      }
      for (int i = 0; i < x_.size(); i++) {
        output.writeDoubleNoTag(x_.getDouble(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(h_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, h_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(f_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, f_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(to_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, to_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hellomsg_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, hellomsg_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getXList().size();
        size += dataSize;
        if (!getXList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        xMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent)) {
        return super.equals(obj);
      }
      org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent other = (org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent) obj;

      if (!getH()
          .equals(other.getH())) return false;
      if (!getF()
          .equals(other.getF())) return false;
      if (!getTo()
          .equals(other.getTo())) return false;
      if (!getHellomsg()
          .equals(other.getHellomsg())) return false;
      if (!getXList()
          .equals(other.getXList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + H_FIELD_NUMBER;
      hash = (53 * hash) + getH().hashCode();
      hash = (37 * hash) + F_FIELD_NUMBER;
      hash = (53 * hash) + getF().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + HELLOMSG_FIELD_NUMBER;
      hash = (53 * hash) + getHellomsg().hashCode();
      if (getXCount() > 0) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + getXList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
        org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.class, org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.Builder.class);
      }

      // Construct using org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        h_ = "";
        f_ = "";
        to_ = "";
        hellomsg_ = "";
        x_ = emptyDoubleList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor;
      }

      @java.lang.Override
      public org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent getDefaultInstanceForType() {
        return org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.getDefaultInstance();
      }

      @java.lang.Override
      public org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent build() {
        org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent buildPartial() {
        org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent result = new org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.h_ = h_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.f_ = f_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.to_ = to_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.hellomsg_ = hellomsg_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          x_.makeImmutable();
          result.x_ = x_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent) {
          return mergeFrom((org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent other) {
        if (other == org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent.getDefaultInstance()) return this;
        if (!other.getH().isEmpty()) {
          h_ = other.h_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getF().isEmpty()) {
          f_ = other.f_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getHellomsg().isEmpty()) {
          hellomsg_ = other.hellomsg_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.x_.isEmpty()) {
          if (x_.isEmpty()) {
            x_ = other.x_;
            x_.makeImmutable();
            bitField0_ |= 0x00000010;
          } else {
            ensureXIsMutable();
            x_.addAll(other.x_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                h_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                f_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                to_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                hellomsg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 41: {
                double v = input.readDouble();
                ensureXIsMutable();
                x_.addDouble(v);
                break;
              } // case 41
              case 42: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                int alloc = length > 4096 ? 4096 : length;
                ensureXIsMutable(alloc / 8);
                while (input.getBytesUntilLimit() > 0) {
                  x_.addDouble(input.readDouble());
                }
                input.popLimit(limit);
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object h_ = "";
      /**
       * <code>string h = 1;</code>
       * @return The h.
       */
      public java.lang.String getH() {
        java.lang.Object ref = h_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          h_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string h = 1;</code>
       * @return The bytes for h.
       */
      public com.google.protobuf.ByteString
          getHBytes() {
        java.lang.Object ref = h_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          h_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string h = 1;</code>
       * @param value The h to set.
       * @return This builder for chaining.
       */
      public Builder setH(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        h_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string h = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearH() {
        h_ = getDefaultInstance().getH();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string h = 1;</code>
       * @param value The bytes for h to set.
       * @return This builder for chaining.
       */
      public Builder setHBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        h_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object f_ = "";
      /**
       * <code>string f = 2;</code>
       * @return The f.
       */
      public java.lang.String getF() {
        java.lang.Object ref = f_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          f_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string f = 2;</code>
       * @return The bytes for f.
       */
      public com.google.protobuf.ByteString
          getFBytes() {
        java.lang.Object ref = f_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          f_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string f = 2;</code>
       * @param value The f to set.
       * @return This builder for chaining.
       */
      public Builder setF(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        f_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string f = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearF() {
        f_ = getDefaultInstance().getF();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string f = 2;</code>
       * @param value The bytes for f to set.
       * @return This builder for chaining.
       */
      public Builder setFBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        f_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>string to = 3;</code>
       * @return The to.
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string to = 3;</code>
       * @return The bytes for to.
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to = 3;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        to_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string to = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        to_ = getDefaultInstance().getTo();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string to = 3;</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        to_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object hellomsg_ = "";
      /**
       * <code>string hellomsg = 4;</code>
       * @return The hellomsg.
       */
      public java.lang.String getHellomsg() {
        java.lang.Object ref = hellomsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hellomsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hellomsg = 4;</code>
       * @return The bytes for hellomsg.
       */
      public com.google.protobuf.ByteString
          getHellomsgBytes() {
        java.lang.Object ref = hellomsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hellomsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hellomsg = 4;</code>
       * @param value The hellomsg to set.
       * @return This builder for chaining.
       */
      public Builder setHellomsg(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        hellomsg_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string hellomsg = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHellomsg() {
        hellomsg_ = getDefaultInstance().getHellomsg();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string hellomsg = 4;</code>
       * @param value The bytes for hellomsg to set.
       * @return This builder for chaining.
       */
      public Builder setHellomsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        hellomsg_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.DoubleList x_ = emptyDoubleList();
      private void ensureXIsMutable() {
        if (!x_.isModifiable()) {
          x_ = makeMutableCopy(x_);
        }
        bitField0_ |= 0x00000010;
      }
      private void ensureXIsMutable(int capacity) {
        if (!x_.isModifiable()) {
          x_ = makeMutableCopy(x_, capacity);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated double x = 5;</code>
       * @return A list containing the x.
       */
      public java.util.List<java.lang.Double>
          getXList() {
        x_.makeImmutable();
        return x_;
      }
      /**
       * <code>repeated double x = 5;</code>
       * @return The count of x.
       */
      public int getXCount() {
        return x_.size();
      }
      /**
       * <code>repeated double x = 5;</code>
       * @param index The index of the element to return.
       * @return The x at the given index.
       */
      public double getX(int index) {
        return x_.getDouble(index);
      }
      /**
       * <code>repeated double x = 5;</code>
       * @param index The index to set the value at.
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(
          int index, double value) {

        ensureXIsMutable();
        x_.setDouble(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double x = 5;</code>
       * @param value The x to add.
       * @return This builder for chaining.
       */
      public Builder addX(double value) {

        ensureXIsMutable();
        x_.addDouble(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double x = 5;</code>
       * @param values The x to add.
       * @return This builder for chaining.
       */
      public Builder addAllX(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureXIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, x_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double x = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        x_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
    }

    // @@protoc_insertion_point(class_scope:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
    private static final org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent();
    }

    public static org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloMsgContent>
        PARSER = new com.google.protobuf.AbstractParser<HelloMsgContent>() {
      @java.lang.Override
      public HelloMsgContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HelloMsgContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloMsgContent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.eclipse.ecf.examples.protobuf.hello.Hellomsg.HelloMsgContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016hellomsg.proto\022\'org.eclipse.ecf.exampl" +
      "es.protobuf.hello\"P\n\017HelloMsgContent\022\t\n\001" +
      "h\030\001 \001(\t\022\t\n\001f\030\002 \001(\t\022\n\n\002to\030\003 \001(\t\022\020\n\010hellom" +
      "sg\030\004 \001(\t\022\t\n\001x\030\005 \003(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_eclipse_ecf_examples_protobuf_hello_HelloMsgContent_descriptor,
        new java.lang.String[] { "H", "F", "To", "Hellomsg", "X", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
