# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hellomsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hellomsg.proto',
  package='org.eclipse.ecf.examples.protobuf.hello',
  syntax='proto3',
  serialized_pb=_b('\n\x0ehellomsg.proto\x12\'org.eclipse.ecf.examples.protobuf.hello\"H\n\x0fHelloMsgContent\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x10\n\x08hellomsg\x18\x03 \x01(\t\x12\t\n\x01x\x18\n \x03(\x01\"R\n\x08HelloMsg\x12\x46\n\x04msgs\x18\n \x03(\x0b\x32\x38.org.eclipse.ecf.examples.protobuf.hello.HelloMsgContentb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HELLOMSGCONTENT = _descriptor.Descriptor(
  name='HelloMsgContent',
  full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hellomsg', full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent.hellomsg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent.x', index=3,
      number=10, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=131,
)


_HELLOMSG = _descriptor.Descriptor(
  name='HelloMsg',
  full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgs', full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsg.msgs', index=0,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=215,
)

_HELLOMSG.fields_by_name['msgs'].message_type = _HELLOMSGCONTENT
DESCRIPTOR.message_types_by_name['HelloMsgContent'] = _HELLOMSGCONTENT
DESCRIPTOR.message_types_by_name['HelloMsg'] = _HELLOMSG

HelloMsgContent = _reflection.GeneratedProtocolMessageType('HelloMsgContent', (_message.Message,), dict(
  DESCRIPTOR = _HELLOMSGCONTENT,
  __module__ = 'hellomsg_pb2'
  # @@protoc_insertion_point(class_scope:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
  ))
_sym_db.RegisterMessage(HelloMsgContent)

HelloMsg = _reflection.GeneratedProtocolMessageType('HelloMsg', (_message.Message,), dict(
  DESCRIPTOR = _HELLOMSG,
  __module__ = 'hellomsg_pb2'
  # @@protoc_insertion_point(class_scope:org.eclipse.ecf.examples.protobuf.hello.HelloMsg)
  ))
_sym_db.RegisterMessage(HelloMsg)


# @@protoc_insertion_point(module_scope)
